### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by petehalverson** [daftspunk/pond#1]
Pouch DB currently stores data in the electron browser which may prove to be problematic.

Consider introducing a [local storage adapter](https://pouchdb.com/adapters.html) and map to a folder defined under the app settings.

**Comment by petehalverson** [comment]
Hmm...further reading on PouchDB's [local storage adapter](https://pouchdb.com/adapters.html) leads me to believe that may not be the best way forward.

Consider move to [knex](knexjs.org) or [electron-json-storage](https://github.com/electron-userland/electron-json-storage)

**Comment by daftspunk** [comment]
Actually I think we need to store everything on the file system as configuration files. See mock `02-01-Create-Project`

1. When user clicks Create Project > Add Existing
1. They are prompted to browse to select an existing project directory
1. Every folder inside that directory maps as a Website
1. The configuration is carried along with it

Each website needs its own config file (portable) and the parent project directory needs on too (project name, image).
